In [2]:
from get_log_data import read_logs, get_labelized_logdata
import pandas as pd
from sklearn.preprocessing import StandardScaler
# COLUMNS = ["DEPTH","DT","GR","LLD","LLS","PHIE","PHIT","RHOB","SW","TNPH","VWCL"]
# FEATURES = ["DEPTH","DT","GR","LLD","LLS","RHOB","TNPH"]
# LABELS = ["phit","phie","sw"]
# LABEL = "phit"
# COLUMNS=[c.lower() for c in COLUMNS]
# FEATURES=[c.lower() for c in FEATURES]
# training_set,prediction_set=read_logs()


In [4]:
X_train,y_train

(array([[-0.99768573,  1.2688609 , -0.6293161 , ..., -0.02743011,
         -1.0924715 , -0.4947934 ],
        [-0.99708587,  0.6900069 , -0.22783814, ..., -0.00897573,
         -0.93708444, -0.95996606],
        [-0.99648607,  0.24695882,  0.01763118, ..., -0.00306188,
         -0.7507544 , -1.2232491 ],
        ...,
        [ 2.271976  , -1.080319  , -0.01070972, ..., -0.14546952,
          0.2078023 ,  1.1392142 ],
        [ 2.2723696 , -1.0539738 ,  0.14975137, ..., -0.1190684 ,
          0.14053515,  1.5288258 ],
        [ 2.2727633 , -0.98644596,  0.09481875, ..., -0.0979475 ,
          0.14053515,  1.2749879 ]], dtype=float32),
 array([8, 8, 8, ..., 2, 3, 3], dtype=int64))

In [6]:
import os
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report,confusion_matrix
X_train, X_test, y_train, y_test=get_labelized_logdata(4)
mlp = MLPClassifier(hidden_layer_sizes=(40,40,40,40))
mlp.fit(X_train,y_train)
predictions = mlp.predict(X_test)

print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
# return classification_report(y_test,predictions)

[[273 321 464 158]
 [  7  12  49  67]
 [  8  15 134  96]
 [  9   0   5 269]]
             precision    recall  f1-score   support

          0       0.92      0.22      0.36      1216
          1       0.03      0.09      0.05       135
          2       0.21      0.53      0.30       253
          3       0.46      0.95      0.62       283

avg / total       0.69      0.36      0.37      1887



In [ ]:
import pandas as pd
import numpy as np

np.random.seed(10)
df = pd.DataFrame({
    'normal': np.random.normal(10, 3, 1000),
    'chi': np.random.chisquare(4, 1000)
})
df.head()

In [ ]:
pd.cut(df['chi'], 8).head()

In [ ]:
custom_bucket_array = np.linspace(0, 20, 9)
custom_bucket_array
df['normal'] = pd.cut(df['normal'], custom_bucket_array)
df['chi'] = pd.cut(df['chi'], custom_bucket_array)
df.head()

In [ ]:
df = pd.DataFrame({
    'normal': np.random.normal(10, 3, 1000),
    'chi': np.random.chisquare(4, 1000)
})
df.head()
pd.qcut(df['chi'], 9, labels=False)